"use client";
import "./globals.css";

import { ThemeProvider, useTheme } from "./context/ThemeContext";
import { useEffect } from "react";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    //But here it remains true.
    const { isDark, setIsDark } = useTheme();
    useEffect(() => {
        setIsDark(false);
    }, []);
    return (
        <ThemeProvider>
            <html lang="en" className={`${isDark ? "dark" : ""}`}>
                <body>{children}</body>
            </html>
        </ThemeProvider>
    );
}
